### ISSUE TITLE
yarn install issue

### ISSUE THREAD

**Issue by amka94amka** [erxes/erxes-api#257]
error An unexpected error occurred: "https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
how to fix?

**Comment by shinebayar-g** [comment]
Develop branch дээр засагдсан байгаа шүү. Цаад сан дээр нь ноцтой алдаа гараад шууд устгасан байгаа. master дээр энэ засвар ороогүй байгаа.
