### ISSUE TITLE
yarn build issue

### ISSUE THREAD

**Issue by amka94amka** [erxes/erxes-api#258]
yarn run v1.9.4$ tsc -p tsconfig.prod.json && cp -rf src/private dist/private
src/data/resolvers/queries/configs.ts:31:23 - error TS2554: Expected 0 arguments, but got 1.31   const info: IInfo = gitRepoInfo(projectPath);
                         ~~~~~~~~~~~~~~~~~~~~~~~~
error Command failed with exit code 2.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by shinebayar-g** [comment]
Дахиад шинээр clone хийгээд yarn install, yarn build хийгээд үзээрэй. yarn build хийхээсээ өмнө .env.sample файлаа .env болгоорой.

**Comment by amka94amka** [comment]
Build хийх гэхлээр ингээд байхын 


yarn run v1.9.4
$ tsc -p tsconfig.prod.json && cp -rf src/private dist/private
src/data/resolvers/queries/configs.ts:31:23 - error TS2554: Expected 0 arguments, but got 1.

31   const info: IInfo = gitRepoInfo(projectPath);
                         ~~~~~~~~~~~~~~~~~~~~~~~~


error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by shinebayar-g** [comment]
Hi @amka94amka энэ асуудал нь манай ашигладаг сан нь шинэчлэгдээд 1 parameter зөрснөөс болж үүссэн юм байна. Тун удахгүй манайх master-луугаа develop branch-аасаа өөрчлөлтүүдээ нэгтгэхээр засагдах юм байна. Хэрвээ хүсвэл develop branch-аас ажиллуулаад үзээрэй.

**Comment by amka94amka** [comment]
okay developer луугаа нэгтгэсний дараагаа хариу өгч болху ?

**Comment by batamar** [comment]
@amka94amka Ene ochigdriin release daraa zasagdsan baigaa shvv pull hiigeerei

**Comment by amka94amka** [comment]
Бүх тохиргоогоо хийгээд ажлуулахаар доорх алдаанууд гарч байна 
 failed: Error during WebSocket handshake: Unexpected response code: 502(client.js:545 )
 Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin
502 (Bad Gateway)(httpLink.js:126)

**Comment by shinebayar-g** [comment]
Тохиргоогоо буруу хийсэн байнаа. Эхлээд ямар нэгэн зүйлгүйгээр local дээрээ ажиллуулаад үз. 4 project тус бүртээ 4 terminal нээгээд yarn dev-ээр ажиллуулаад үз. Нэг л ойлгохгүй л байна даа. Эсвэл зүгээр docker зааврын дагуу хийгээд үзэх үү?

**Comment by amka94amka** [comment]
ууг нь згр суулгаад ажлуулсан юмаа тэгсэн ssl нэмснээс хойш ингээд алдаа гарчаад байган

**Comment by shinebayar-g** [comment]
SSL-тэй болсон бол .env файлын http, болон ws-үүдийг https, wss болгоно. Nginx ашиглаж байгаа биздээ?

**Comment by amka94amka** [comment]
мхм тэр бүгдийг хийцэн байгаа

**Comment by shinebayar-g** [comment]
502 гэхээрээ reverse proxy чинь нэг бол ажиллахгүй байна, үгүй бол буруу тохируулсан 2 л шалтгаантай.

**Comment by amka94amka** [comment]
nginx config оо 1 file дотор биш 4 хуваагаад бичцэн байгаа тэрнээс болсын болу ?

**Comment by shinebayar-g** [comment]
4-үүлээ include хийгдсэн юм уу? nginx.conf дотроо

**Comment by shinebayar-g** [comment]
https://github.com/erxes/erxes/wiki/Running-behind-Nginx

Энэ хуудсыг сайн уншаад үзээрэй. Сүүлд янз янзаар тохируулах заавар оруулсан байгаа.
Эхлээд SSL-гүй тохируулаад үз. Дараа нь .env дээрээ ssl-тэй болгоод nginx дээрээ SSL-ээ оруулаад өгөхөд ямар ч асуудалгүй.

**Comment by shinebayar-g** [comment]
За бүр болохгүй бол би өнөө орой 1 заавар блогтоо оруулая аа. :)

**Comment by amka94amka** [comment]
за тгээч хө :))

**Comment by shinebayar-g** [comment]
https://medium.com/@shinebayar.g/5-%D0%BC%D0%B8%D0%BD%D1%83%D1%82%D1%8B%D0%BD-%D0%B4%D0%BE%D1%82%D0%BE%D1%80-erxes-%D0%B8%D0%B9%D0%B3-%D1%81%D1%83%D1%83%D0%BB%D0%B3%D0%B0%D1%85-%D0%BD%D1%8C-d92ba007acdb

Good luck.
