### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by amka94amka** [erxes/erxes-api#286]
Build хийх гэхлээр ингээд байхын

yarn run v1.9.4
$ tsc -p tsconfig.prod.json && cp -rf src/private dist/private
src/data/resolvers/queries/configs.ts:31:23 - error TS2554: Expected 0 arguments, but got 1.

31 const info: IInfo = gitRepoInfo(projectPath);
~~~~~~~~~~~~~~~~~~~~~~~~

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by shinebayar-g** [comment]
Duplicate: https://github.com/erxes/erxes-api/issues/258
