### ISSUE TITLE
Add support for S3 Compatible Object Storage

### ISSUE THREAD

**Issue by alekseyp** [erxes/erxes-api#362]
It's a good idea to support s3 compatible services like minio.

In order for them to work, we need to add `endpoint` and `s3ForcePathStyle` params.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html

https://github.com/erxes/erxes-api/blob/4f26d50ddff861bdefb08888200c28f5746a62fc/src/data/utils.ts#L64

**Comment by marcnet80** [comment]
Hi, @alekseyp. I will take it.
