### ISSUE TITLE
[ Help required ] for multiple teams.

### ISSUE THREAD

**Issue by veerjainATgmail** [erxes/erxes-api#475]
Hi, 

We would like to host erxes in th locally for two different teams, like
team1.erxes.ourdomain.com and
team2.erxes.ourdomain.com with separate team admins.
preferrably sharing the same server. 

Wondering, if there is a way other than creating two separate instances?

Thanks,
Veer

**Comment by shinebayar-g** [comment]
Hi @veerjainATgmail , single erxes instance cannot bind on 2 different subdomain. It's possible to manage multiple teams with single instance. However admin roles will be able to see each other team's content. In that case you could lock down global admin user and manage permissions.

**Comment by veerjainATgmail** [comment]
Hi @shinebayar-g,
Thats a very good suggestion. Thanks.
