### ISSUE TITLE
Multiple tenant to support teams with own admins

### ISSUE THREAD

**Issue by veerjainATgmail** [erxes/erxes-api#514]
**Is your feature request related to a problem? Please describe.**

Ability to create small teams under separate admins, accessible through subdomain for each teams.

**Describe the solution you'd like**

Implement using
http://nmajor.com/posts/multi-tenancy-with-expressmongoose
Passing the team name from the subdomain or tenantless user database lookup.

**Additional context**

This will reduce the server resources required to host teams.

**Comment by mendorshikh** [comment]
@veerjainATgmail This is basically as similar as to our SaaS. So we will not support this issue :) I hope u get it right.

**Comment by veerjainATgmail** [comment]
@mendorshikh Sure.. Thanks ! :+1: :slightly_smiling_face:
