### ISSUE TITLE
Deepcode - Fix the bugs 

### ISSUE THREAD

**Issue by Batchimegb** [erxes/erxes-api#521]
1. https://www.deepcode.ai/app/gh/erxes/erxes-widgets-api/09037692b59ac4f5be290d8dcc20046b83e24636/_/dashboard/
2. https://www.deepcode.ai/app/gh/erxes/erxes-api/a560f66929dcac9cfeac3f65c480201971fda926/_/dashboard/
3. https://www.deepcode.ai/app/gh/erxes/erxes-logger/3047c8d73d05c6273ee774cb6a3191e566b28d54/_/dashboard/
4. https://www.deepcode.ai/app/gh/erxes/erxes-engages-email-sender/e694a22328cd172fb483e57ab12d008778130e12/_/dashboard/
5. https://www.deepcode.ai/app/gh/erxes/erxes-insights/d1df1238dd07cf54addc6edc2d077ac0571b7d03/_/dashboard/

**Comment by marcnet80** [comment]
@Batchimegb, I can look if these bugs related to back-end part.

**Comment by batamar** [comment]
@marcnet80 That would be great

**Comment by marcnet80** [comment]
@batamar, could you please provide me access to deepcode dashboard? I can't open above links.

**Comment by batamar** [comment]
@marcnet80 Click on the link, log in with your github account then click authorize will be redirected to dashboard

**Comment by marcnet80** [comment]
@batamar, got it, thank you.

**Comment by marcnet80** [comment]
Pull-requests added.
