### ISSUE TITLE
src/db/models/Users.ts(499,17): error TS2339: Property 'user' does not exist on type 'string | object'.

### ISSUE THREAD

**Issue by AravindR7** [erxes/erxes-api#649]
**Describe the bug**
When I run yarn dev or yarn start it dosent start the server and no code was edited before running those commands and throws the below mentioned error...
[ERROR] 10:59:02 ⨯ Unable to compile TypeScript:
src/db/models/Users.ts(499,17): error TS2339: Property 'user' does not exist on type 'string | object'.

**To Reproduce**
1. Go to the root of repository in command prompt
2.Run yarn install
3.Run yarn start/dev it throws typescript error

**Expected behavior**
Its supposed to start the server and then enter login details on the client side(expected behaviour)

![Screenshot from 2019-11-27 11-07-57](https://user-images.githubusercontent.com/45995781/69697190-d38e8f00-1107-11ea-8d58-24628594042c.png)

**Context (please include the related information if applicable):**
 - OS: [ Ubuntu 18.04.3]

**Comment by batamar** [comment]
Hi @AravindR7. On which branch are you running `erxes-api`

**Comment by AravindR7** [comment]
Tried on both master and develop

**Comment by batamar** [comment]
Did you try removing node_modules folder and rerun yarn install?

**Comment by AravindR7** [comment]
No yarn install was throwing an error so I ran yarn cache clean and then ran yarn install
