### ISSUE TITLE
Usage of UPLOAD_SERVICE_TYPE is prevented due typo in name 

### ISSUE THREAD

**Issue by theikkila** [erxes/erxes-api#708]
**Describe the bug**
Using `UPLOAD_SERVICE_TYPE` for defining other than `AWS` as service type will fail due typo @ https://github.com/erxes/erxes-api/blob/master/src/data/utils.ts#L246

**To Reproduce**
1. Use any other than `AWS` as `UPLOAD_SERVICE_TYPE`
2. Try to upload something such as new avatar picture.
3. When API is used for fetching the image `<api>/read-file?key=<key>` it will fail with following error message

```
AWS credentials are not configured
```

**Expected behavior**
See a picture or other uploaded file

 - erxes version: 0.12.3

**Additional context**
 #707 wil fix this

**Comment by batamar** [comment]
Fixed
