### ISSUE TITLE
Remove DOMAIN envs

### ISSUE THREAD

**Issue by batamar** [erxes/erxes-api#747]
**Is your enhancement request related to a problem? Please describe.**
Configuring too many env variables is making the deployment process hard. So reducing all possible env variables.

**Describe the solution you'd like**
Getting backend domain from request cookies

Generated default values for ```WORKERS_API_DOMAIN, CRONS_API_DOMAIN, INTERATIONS_API_DOMAIN, ENGAGES_API_DOMAIN, LOGGER_DOMAIN``` based on MAIN_APP_DOMAIN like following

```${MAIN_APP_DOMAIN}/integrations```

**Comment by SorJEF** [comment]
This is actually really useful when you deploy the app using docker. Each docker instance has its own domain based on the service name. Removing these variables will prevent deploying with docker and with any docker related services, like Kubernetes for instance.
